### ISSUE TITLE
Implement Projector

### ISSUE THREAD

**Issue by nicktripp** [benstoehr/GoldTeamTrack2#16]
@trueb2 More info about this?

**Comment by trueb2** [comment]
The Projector will receive a list of tuples and a list of table columns to project. 

The list of tuples will be the starting location of a row in a table for each table that needs to be read for the resulting projection. The rows from a table will be projected as described by the list of table columns supplied as an argument. 

The cartesian product for rows to be read should already be done or supplied in generator form for Projector. The projector should only have logic for reading from multiple tables and projecting the correct columns.
